name = "cafe"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "__NEXT_ON_PAGES__KV_SUSPENSE_CACHE"
id = "9a2b203829934a39bbd1b8646cf6118d"

[vars]
NEXT_PUBLIC_CLIENT_SLUG = "demo-cafe"
NEXT_PUBLIC_SITE_URL = "http://localhost:3000"
NEXT_PUBLIC_TIER = "premium"
NEXT_PUBLIC_RESERVATIONS = "true"
NEXT_PUBLIC_MULTI_BRANCH = "true"
NEXT_PUBLIC_BILINGUAL = "false"
NEXT_PUBLIC_SECONDARY_LOCALE = "hi"
NEXT_PUBLIC_THEME = "mercado"
